import 'package:mars_flutter/data/asset_paths_gen/assets.gen.dart';

enum CardResource {
  ANIMAL,
  MICROBE,
  FIGHTER,
  SCIENCE,
  FLOATER,
  ASTEROID,
  PRESERVATION,
  CAMP,
  DISEASE,
  RESOURCE_CUBE,
  DATA,
  SYNDICATE_FLEET,
  VENUSIAN_HABITAT,
  SPECIALIZED_ROBOT,
  SEED,
  AGENDA,
  ORBITAL,
  GRAPHENE,
  HYDROELECTRIC_RESOURCE,
  CLONE_TROOPER,
  TOOL,
  WARE,
  SCOOP,
  JOURNALISM,
  ACTIVIST,
  SUPPLY_CHAIN;

  static const _TO_STRING_MAP = {
    ANIMAL: 'Animal',
    MICROBE: 'Microbe',
    FIGHTER: 'Fighter',
    SCIENCE: 'Science',
    FLOATER: 'Floater',
    ASTEROID: 'Asteroid',
    PRESERVATION: 'Preservation',
    CAMP: 'Camp',
    DISEASE: 'Disease',
    RESOURCE_CUBE: 'Resource cube',
    DATA: 'Data',
    SYNDICATE_FLEET: 'Syndicate Fleet',
    VENUSIAN_HABITAT: 'Venusian Habitat',
    SPECIALIZED_ROBOT: 'Specialized Robot',
    SEED: 'Seed',
    AGENDA: 'Agenda',
    ORBITAL: 'Orbital',
    GRAPHENE: 'Graphene',
    HYDROELECTRIC_RESOURCE: 'Hydroelectric resource',
    CLONE_TROOPER: 'Clone Trooper',
    TOOL: 'Tool',
    WARE: 'Ware',
    SCOOP: 'Scoop',
    JOURNALISM: 'Journalism',
    ACTIVIST: 'Activist',
    SUPPLY_CHAIN: 'Supply Chain',
  };

  static final _TO_IMAGE_PATH_MAP = {
    ANIMAL: Assets.resources.animal.path,
    MICROBE: Assets.resources.microbe.path,
    FIGHTER: Assets.resources.fighter.path,
    SCIENCE: Assets.resources.science.path,
    FLOATER: Assets.resources.floater.path,
    ASTEROID: Assets.resources.asteroid.path,
    PRESERVATION: Assets.resources.preservation.path,
    CAMP: Assets.resources.camp.path,
    DISEASE: Assets.resources.disease.path,
    RESOURCE_CUBE: Assets.cube.path,
    DATA: Assets.resources.data.path,
    SYNDICATE_FLEET: Assets.resources.syndicateFleet.path,
    VENUSIAN_HABITAT: Assets.resources.venusianHabitat.path,
    SPECIALIZED_ROBOT: Assets.resources.specializedRobot.path,
    SEED: Assets.resources.seed.path,
    AGENDA: Assets.resources.agenda.path,
    ORBITAL: Assets.resources.orbital.path,
    GRAPHENE: Assets.resources.graphene.path,
    HYDROELECTRIC_RESOURCE: Assets.resources.hydroelectricResource.path,
    CLONE_TROOPER: Assets.resources.cloneTrooper.path,
    TOOL: Assets.underworld.cardResourceTool.path,
    WARE: Assets.underworld.cardResourceWare.path,
    SCOOP: Assets.underworld.cardResourceScoop.path,
    JOURNALISM: Assets.underworld.cardResourceJournalism.path,
    ACTIVIST: Assets.underworld.cardResourceActivist.path,
    SUPPLY_CHAIN: Assets.underworld.cardResourceSupplyChain.path,
  };
  static final _TO_ENUM_MAP =
      _TO_STRING_MAP.map((key, value) => MapEntry(value, key));
  String? toImagePath() => _TO_IMAGE_PATH_MAP[this];
  @override
  String toString() => _TO_STRING_MAP[this] ?? 'Unknown';
  static CardResource? fromString(String value) => _TO_ENUM_MAP[value];
}
